---
kind: pipeline
type: docker
name: default

workspace:
  path: /drone/src

volumes:
  - name: cache
    temp: { }

environment:
  GOCACHE: /cache/go/build
  GOMODCACHE: /cache/go/download

steps:
  - name: deps
    image: golang:1.18.4-alpine3.15
    volumes:
      - name: cache
        path: /cache
    commands:
      - apk --no-cache add git
      - cd src
      - go get -t -d -v ./...
      - go build all
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags
  - name: release
    image: golang:1.18.4-alpine3.15
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    privileged: false
    volumes:
      - name: cache
        path: /cache
    commands:
      - export VERSION=${DRONE_TAG}
      - apk add git
      - go install github.com/goreleaser/goreleaser@latest
      - cd ./src/
      - goreleaser release -f ../.goreleaser-stable.yaml
    depends_on:
      - fetch
    when:
      ref:
        include:
          - refs/tags/v*.*.*
        exclude:
          - refs/tags/v*.*.*-beta*
  - name: beta-release
    image: golang:1.18.4-alpine3.15
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    privileged: false
    volumes:
      - name: cache
        path: /cache
    commands:
      - apk add git
      - export VERSION=${DRONE_TAG}
      - go install github.com/goreleaser/goreleaser@latest
      - cd ./src/
      - goreleaser release -f ../.goreleaser-beta.yaml
    depends_on:
      - fetch
    when:
      ref:
        - refs/tags/v*.*.*-beta*
trigger:
  event:
    - tag