---
kind: pipeline
type: docker
name: default

workspace:
  path: /drone/src
volumes:
  - name: cache
    temp: { }
environment:
  GOCACHE: /cache/go/build
  GOMODCACHE: /cache/go/download
steps:
  - name: deps
    image: golang:1.18.4-alpine3.15
    volumes:
      - name: cache
        path: /cache
    commands:
      - apk --no-cache add git
      - go get -t -d -v ./...
      - go build all
  - name: test
    image: golang:1.18.4-alpine3.15
    environment:
      STAGING_EMAIL:
        from_secret: STAGING_EMAIL
      STAGING_PASSWORD:
        from_secret: STAGING_PASSWORD
    volumes:
      - name: cache
        path: /cache
    commands:
      - go test -race -coverprofile=/cache/coverage.txt -covermode=atomic ./...
    depends_on:
      - deps
  - name: coverage
    image: alpine:3.15
    volumes:
      - name: cache
        path: /cache
    environment:
      CODECOV_TOKEN:
        from_secret: CODECOV_TOKEN
    commands:
      - apk --no-cache add bash curl
      - curl -L https://codecov.io/bash -o /usr/local/bin/codecov
      - chmod +x /usr/local/bin/codecov
      - /usr/local/bin/codecov -f /cache/coverage.txt
    depends_on:
      - test
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags
    when:
      event:
        - tag
  - name: release
    image: golang:1.18.4-alpine3.15
    environment:
      PRODUCTION_FIREBASE_API_KEY:
        from_secret: PRODUCTION_FIREBASE_API_KEY
      PRODUCTION_API_URL:
        from_secret: PRODUCTION_API_URL
      SENTRY_DSN:
       from_secret: SENTRY_DSN
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    privileged: false
    volumes:
      - name: cache
        path: /cache
    commands:
      - export VERSION=${DRONE_TAG}
      - apk add wget
      - wget -q  -P /tmp https://github.com/goreleaser/goreleaser/releases/download/v1.10.2/goreleaser_1.10.2_x86_64.apk
      - apk add --allow-untrusted /tmp/goreleaser_1.10.2_x86_64.apk
      - goreleaser release
    depends_on:
      - test
    when:
      event:
        - tag
trigger:
  event:
    - push
    - tag
