---
kind: pipeline
type: docker
name: default

workspace:
  path: /drone/src

volumes:
  - name: cache
    temp: { }

environment:
  GOCACHE: /cache/go/build
  GOMODCACHE: /cache/go/download

steps:
  - name: deps
    image: golang:1.18.4
    volumes:
      - name: cache
        path: /cache
    commands:
      - apt update
      - apt install git -y
      - cd src
      - go get -t -d -v ./...
      - go build all
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags
  - name: test
    image: golang:1.18.4
    volumes:
      - name: cache
        path: /cache
    depends_on:
      - deps
    commands:
      - apt update
      - apt install build-essential -y
      - cd src
      - go test ./...
  - name: release
    image: golang:1.18.4-bullseye
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    privileged: false
    volumes:
      - name: cache
        path: /cache
    commands:
      - export VERSION=${DRONE_TAG}
      - go install github.com/goreleaser/goreleaser@latest
      - cd ./src
      - goreleaser build -f ../.goreleaser-stable.yaml
      - apt update
      - apt install git binutils -y
      - cd ./ipkg/src
      - ./build.sh
      - cd ../../src
      - goreleaser release -f ../.goreleaser-stable.yaml
    depends_on:
      - test
    when:
      ref:
        include:
          - refs/tags/v*.*.*
          - refs/tags/v*.*.*-post*
        exclude:
          - refs/tags/v*.*.*-beta*
  - name: beta-release
    image: golang:1.18.4-bullseye
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    privileged: false
    volumes:
      - name: cache
        path: /cache
    commands:
      - export VERSION=${DRONE_TAG}
      - apt update
      - apt install git binutils -y
      - go install github.com/goreleaser/goreleaser@latest
      - cd packages
      - build.sh
      - cd ../src
      - goreleaser release -f ../.goreleaser-beta.yaml
    depends_on:
      - test
    when:
      ref:
        - refs/tags/v*.*.*-beta*
trigger:
  event:
    - tag